-- MySQL Script generated by MySQL Workbench
-- Sat Mar 15 02:03:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema posdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `posdb` ;

-- -----------------------------------------------------
-- Table `posdb`.`cancel_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`cancel_reason` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT 'ชื่อเหตุผลในการยกเลิก',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'คำอธิบายเพิ่มเติม',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บเหตุผลในการยกเลิกรายการอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL COMMENT 'ชื่อหมวดหมู่',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บหมวดหมู่สินค้า';


-- -----------------------------------------------------
-- Table `posdb`.`table_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`table_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT 'ชื่อสถานะโต๊ะ เช่น ว่าง, ไม่ว่าง,',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บสถานะของโต๊ะอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`dining_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`dining_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `table_number` VARCHAR(10) NOT NULL COMMENT 'หมายเลขโต๊ะ',
  `status_id` INT NOT NULL COMMENT 'รหัสสถานะโต๊ะ',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `table_number_UNIQUE` (`table_number` ASC) VISIBLE,
  INDEX `fk_table_status_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_table_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `posdb`.`table_status` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บข้อมูลโต๊ะอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'เวลาเริ่มใช้โต๊ะ',
  `end_time` TIMESTAMP NULL DEFAULT NULL COMMENT 'เวลาสิ้นสุดการใช้โต๊ะ',
  `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'สถานะ: A=Active, C=Completed, V=Void',
  `table_id` INT NOT NULL COMMENT 'รหัสโต๊ะ',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_order_table_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_table`
    FOREIGN KEY (`table_id`)
    REFERENCES `posdb`.`dining_table` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 197
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บข้อมูลการสั่งอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT 'ชื่อสินค้า',
  `price` DECIMAL(10,2) NOT NULL COMMENT 'ราคาสินค้า',
  `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'สถานะ: A=Active, I=Inactive',
  `image_url` VARCHAR(255) NULL DEFAULT NULL COMMENT 'URL รูปภาพสินค้า',
  `category_id` INT NOT NULL COMMENT 'รหัสหมวดหมู่',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `posdb`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บข้อมูลสินค้า';


-- -----------------------------------------------------
-- Table `posdb`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL COMMENT 'จำนวนที่สั่ง',
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT 'ราคาต่อหน่วย',
  `status` CHAR(1) NOT NULL DEFAULT 'P' COMMENT 'สถานะ: P=Processing, C=Completed, V=Void',
  `order_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'เวลาที่สั่งอาหารแต่ละรายการ',
  `order_id` INT NOT NULL COMMENT 'รหัสออเดอร์',
  `product_id` INT NOT NULL COMMENT 'รหัสสินค้า',
  `cancel_reason_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_detail_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_detail_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_detail_cancel_reason_idx` (`cancel_reason_id` ASC) VISIBLE,
  CONSTRAINT `fk_detail_cancel_reason`
    FOREIGN KEY (`cancel_reason_id`)
    REFERENCES `posdb`.`cancel_reason` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detail_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `posdb`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `posdb`.`product` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 650
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บรายละเอียดการสั่งอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(1) NOT NULL COMMENT 'รหัสสถานะ A=Active,  C=Completed, V=Void',
  `name` VARCHAR(50) NOT NULL COMMENT 'ชื่อสถานะ',
  `type` VARCHAR(20) NOT NULL COMMENT 'ประเภทสถานะ normal=ทั่วไป, cancel=ต้องระบุเหตุผลการยกเลิก',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'คำอธิบาย',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตารางเก็บสถานะของรายการอาหาร';


-- -----------------------------------------------------
-- Table `posdb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posdb`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL COMMENT 'ยอดเงินรวม',
  `payment_method` VARCHAR(20) NOT NULL,
  `payment_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาชำระเงิน',
  `status` CHAR(1) NOT NULL DEFAULT 'S' COMMENT 'สถานะ: S=Success, F=Failed, P=Pending',
  `reference` VARCHAR(50) NULL DEFAULT NULL COMMENT 'เลขอ้างอิงการชำระเงิน (ถ้ามี)',
  `order_id` INT NOT NULL COMMENT 'รหัสออเดอร์',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `posdb`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
